### ISSUE TITLE
reproducing Fig 1c from final paper

### ISSUE THREAD

**Issue by rtyags** [vangalenlab/MAESTER-2021#2]
Hi,

I couldn't figure out which part of the code given here refers to Fig 1c in the final paper (i.e. MAESTER variant recovery plot with blue bars). The paper doesn't make it clear what the definition of these metrics is. does the heteroplasmy threshold X refer to bulk heteroplasmy of said variant? I suspect that's true, but just wanted to confirm it from the code, but can't find the code here. 

Thanks

**Comment by petervangalen** [comment]
Hi, good question, this panel is not represented in the repository because it was made by Caleb Lareau. Your question is if the heteroplasmy X represents the level detected in bulk or single-cell ATAC-seq? I will ask him and get back to you.

**Comment by petervangalen** [comment]
Caleb: "It's heteroplasmy within a single cell for a single variant. Given that it is covered in both ATAC and RNA, we make ATAC the true positive and ask how successful are we at recovering it in MAESTER"

I do remember the number of variants underlying the data decreases towards the right. I hope that helps.

**Comment by rtyags** [comment]
Thanks for the response Peter and Caleb. Just to clarify, the metric is just a True Positive recovery rate, and doesn't indicate the False Positive rate. i.e. while it shows that maester is highly sensitive, it doesn't show is the specificity was good or poor. Is that right?

**Comment by petervangalen** [comment]
That is right.
